inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

# This cop requires required_ruby_version and TargetRubyVersion to be equal
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'gherkin.gemspec'